### ISSUE TITLE
require msnodesqlv8 giving the error in cypress - Error: None of the binaries loaded successfully 

### ISSUE THREAD

**Issue by rodrigrichrod** [TimelordUK/node-sqlserver-v8#112]
require msnodesqlv8 giving the error in cypress - Error: None of the binaries loaded successfully 

I am trying to run msnodesqlv8 in cypress and I get the following output:

 Error: None of the binaries loaded successfully. Is your node version >= 10.15 ?
    at failIfNoBinaryExported (C:\node_modules\msnodesqlv8\lib\bootstrap.js:64:15)
    at Object.liveLoad (C:\node_modules\msnodesqlv8\lib\bootstrap.js:51:5)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\bootstrap.js:80:12)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\bootstrap.js:82:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at connectionModule (C:\node_modules\msnodesqlv8\lib\connection.js:10:21)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\connection.js:445:3)
    at Object.<anonymous> (C:\node_modules\msnodesqlv8\lib\connection.js:449:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)

I am using the latest version of msnodesqlv8:
"msnodesqlv8": {
      "version": "0.8.3",
      "resolved": "https://registry.npmjs.org/msnodesqlv8/-/msnodesqlv8-0.8.3.tgz"}

This is the only module that I have not been able to run in cypress.  All other modules work
including mssql and tedious.  It works fine if I just have a regular node project, but only throws this error when trying to run it in cypress.

Please advise.

**Comment by rodrigrichrod** [comment]
It turns out Cypress tasks run with Node v8.9.3 and this latest version of msnodesqlv8 requires node version > 10.15.
