### ISSUE TITLE
Min version for Native Client 11.0 on Windows Server

### ISSUE THREAD

**Issue by murphman300** [TimelordUK/node-sqlserver-v8#115]
Hi all,

Currently having an issue trying to connect from a Windows Server 2016  VM running version 11.0.7001.0. Using Trusted_Connection=true for windows intgerated authentication, we keep getting a timeout on the login step.

However, this same script connects perfectly if run from a Windows Enterprise device which runs 11.0.7469.

Is there a reason for this? or is anyone else experiencing this?

Or is there a specific OS requirement for mssql/msnodesqlv8 to operate as intended on a Windows Server vm?

Any insight would be great.

Script:

`
     
        const sql = require('mssql/msnodesqlv8')

	let C = new sql.ConnectionPool({
        connectionString: 'Driver={SQL Server Native Client 11.0};Server=domain;Database=dbname;Trusted_Connection=yes'
    })

`

**Comment by murphman300** [comment]
The error:

`{ ConnectionError: Error: [Microsoft][SQL Server Native Client 11.0]TCP Provider: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
,Error: [Microsoft][SQL Server Native Client 11.0]Login timeout expired,Error: [Microsoft][SQL Server Native Client 11.0]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online.
    at msnodesql.open (C:\Users\q.jlmurphy\AppData\Roaming\npm\node_modules\mssql\lib\msnodesqlv8.js:192:17)
    at Immediate.setImmediate (C:\Users\q.jlmurphy\AppData\Roaming\npm\node_modules\msnodesqlv8\lib\connection.js:361:15)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5) code: undefined, name: 'ConnectionError' }`

**Comment by murphman300** [comment]
Other note: version 11.0.7469 cannot install on Windows Server due to incompatibility.

**Comment by TimelordUK** [comment]
If you see which port is open accepting tcp connections on vm can you actually telnet to that port from outside. Typically these issues are network related I assume a test connection can be made from running on the host itself.  

Have you tried looking with a sniffer such as wireshark to see if an actual connection can be established.  Is the port open on firewall. 

The code is a wrapper around the ODBC library there is nothing to stop library from working providing the transport can be opened.

**Comment by TimelordUK** [comment]
closing no activity
