### ISSUE TITLE
msnodesqlv8 version 0.1.28 tries to run 'node-gyp rebuild' during 'npm install'

### ISSUE THREAD

**Issue by alykoshin** [TimelordUK/node-sqlserver-v8#13]
While any other versions up to 0.1.28 allowed to install binaries without 'node-gyp rebuild'

Log is below:
```
C:\app\test_npm_install>npm install
npm WARN package.json analysis-data-api@0.0.0 No README data
npm WARN package.json analysis-data-api@0.0.0 license should be a valid SPDX lic
ense expression
/
> msnodesqlv8@0.1.29 install C:\app\test_npm_install\node_modules\msnodesqlv8
> node-gyp rebuild


C:\app\test_npm_install\node_modules\msnodesqlv8>if not defined npm_config_node_
gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  reb
uild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Users\Administrator\AppData\Roamin
g\npm\node_modules\npm\node_modules\node-gyp\lib\install.js:377:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (C:\Users\Administrator\AppData\
Roaming\npm\node_modules\npm\node_modules\request\request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)

gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator
\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gy
p.js" "rebuild"
gyp ERR! cwd C:\app\test_npm_install\node_modules\msnodesqlv8
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\A
ppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! msnodesqlv8@0.1.29 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msnodesqlv8@0.1.29 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the msnodesqlv8 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls msnodesqlv8
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\app\test_npm_install\npm-debug.log

C:\app\test_npm_install>
```

**Comment by TimelordUK** [comment]
sorry, please update - I unfortunately messed up the release, it should not do a gyp rebuild on >= 0.1.35

**Comment by alykoshin** [comment]
Thank you very much for your work and prompt response.
