### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by rusandreev** [TimelordUK/node-sqlserver-v8#161]
The library works very well on the local machine, but I am getting an error trying to build on a TeamCity and deploy it to the server.

Node.js version - v12.16.2 (on local machine and server)

`Application has thrown an uncaught exception and is terminated:
Error: Cannot open C:\TeamCity\BuildAgent_3\work\df0f347335528399\node_modules\msnodesqlv8\build\Release\sqlserverv8.node: Error: The specified module could not be found.

C:\TeamCity\BuildAgent_3\work\df0f347335528399\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
    at Object.<anonymous> (C:\inetpub\Dev\Web\build\main-server.js:198891:216)
    at Object.<anonymous> (C:\inetpub\Dev\Web\build\main-server.js:198892:30)
    at __webpack_require__ (C:\inetpub\Dev\Web\build\main-server.js:26:30)
    at C:\inetpub\Dev\Web\build\main-server.js:85601:21
    at Object.<anonymous> (C:\inetpub\Dev\Web\build\main-server.js:86037:3)
    at __webpack_require__ (C:\inetpub\Dev\Web\build\main-server.js:26:30)
    at Object.<anonymous> (C:\inetpub\Dev\Web\build\main-server.js:85528:12)
    at Object.<anonymous> (C:\inetpub\Dev\Web\build\main-server.js:85585:30)
    at __webpack_require__ (C:\inetpub\Dev\Web\build\main-server.js:26:30)
    at Object.<anonymous> (C:\inetpub\Dev\Web\build\main-server.js:198801:19)`

Any thoughts?

**Comment by mtriff** [comment]
That module should be downloaded during `npm install`. Are you running `npm install` during in your build script? If so, can you provide the output?

**Comment by rusandreev** [comment]
Yes, I am running Yarn install. Here is the output:

**Comment by TimelordUK** [comment]
the library recently was moved to use prebuild see package.json

basically on each target machine you have to install the msnodeslv8 package
as the executable is not provided in the npm package - rather it is fetched
and placed into Release is your platform is supported else it will try and
compile the code based on your specific version.   Given you are using
teamcity your server may not be permissioned to perform the fetch from
git?  you either need a step in team city to perform the install where
prebuld fetches the correct version, or you need to build it locally on
your box - or I guess if you know the version you are running you could
manually place the binary into Release folder.


```cmd

"install": "prebuild-install || node-gyp rebuild",

```

**Comment by rusandreev** [comment]
I think fetching from git in TeamCity is ok since I have a bunch of npm packages and I didn't have a problem with installing them. 

Could it be a problem with Yarn? Since I user yarn command to install npm packages.

**Comment by TimelordUK** [comment]
have you got administrator who can logon to the build server - find where
the package has been installed and manually run install yourself and check
the release folder to see if the binary has been populated.  Then we
firstly know your server at least can install and it is more how the
components are being installed

**Comment by rusandreev** [comment]
I can login to the build server now and checked the package: there is a sqlserverv8.node file in the proper place. But anyway I am getting an error` Error: Cannot open C:\TeamCity\BuildAgent_4\work\df0f347335528399\node_modules\msnodesqlv8\build\Release\sqlserverv8.node: Error: The specified module could not be found.`

**Comment by DanMccloy** [comment]
For me this was an issue with Webpack and how it was handling the sqlserverv8.node file with node-loader. 

When building locally it would run fine - but node-loader/webpack was setting an absolute path to the module, meaning it would not run correctly when moved to another machine. The module itself was getting included in the bundle - but the path leading to it was wrong.

I changed my Webpack config up and included msnodesqlv8 as an external, then copied the msnodesqlv8 folder across separately using CopyPlugin.

**Comment by rusandreev** [comment]
@DanMccloy can you put here a Webpack config with CopyPlugin part? I'll really appreciate it

**Comment by DanMccloy** [comment]
This is what worked for me - this was my renderer config, as I'm using Electron. Just for reference I was also using version 0.6.0 of node-loader and 4.43.0 of webpack.

`const path = require('path');
const CopyPlugin = require('copy-webpack-plugin');
const webpack = require('webpack')

module.exports = {
      resolve: {
        extensions: ['.js', '.jsx', '.json', '.css', '.ttf'],
      },
      externals: [{
        msnodesqlv8: './node_modules/msnodesqlv8',
      }],
      output: {
        libraryTarget: 'commonjs2',
      },
      module:{
        rules:[
          {
            test: /\.node$/,
            use: 'node-loader',
          },
          {
            test: /\.(m?js|node)$/,
            parser: { amd: false },
            use: {
              loader: '@marshallofsound/webpack-asset-relocator-loader',
              options: {
                outputAssetBase: 'native_modules',
              },
            },
          },
            {
                test: /\.(png|jp(e*)g|svg|gif)$/,  
                use: [{
                    loader: 'file-loader',
                    options: { 
                        name: '[name].[ext]',
                        outputPath: 'images/',
                    } 
                }]
            },
            {
                test:/\.css$/,
                use:['style-loader','css-loader']
            } , {
                test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
                use: [{
                    loader: 'file-loader',
                    options: {
                        name: '[name].[ext]',
                        outputPath: 'fonts/'
                    }
                }]
            } ,
            {
              test: /\.(html)$/,
              use: {
                loader: 'html-loader',
              }
            },
            {
              test: /\.worker.js$/,
              loader: 'worker-loader',
              options: { inline: true },
            },
            {
              test: /\.(js|jsx|ts|tsx)$/,
              exclude: /node_modules/,
              use: "babel-loader",
            }
       ]
    },
    plugins: [
        new CopyPlugin([
          { from: './node_modules/msnodesqlv8', to: './node_modules/msnodesqlv8' },
          { from: './node_modules/msnodesqlv8', to: './main/node_modules/msnodesqlv8' }
        ])
      ]
};
`

**Comment by Almusamim** [comment]
I'm having same problem with Quasar.. 
And can't figure out how to solve it!!!

node-loader:
Error: The specified module could not be found.

![image](https://user-images.githubusercontent.com/16979898/94532016-9e7a2e00-023d-11eb-8e42-8ec1f89e1efb.png)

**Comment by rusandreev** [comment]
Thanks, @DanMccloy. I changed the Webpack config and this error is gone. But now I am getting a connection error:
`code: 0
sqlstate: "IM002"` 
And this error is appearing only on the dev machine. On the local machine everything is ok.

@DanMccloy can you say for what reason did you use this rule in config:
`        {
            test: /\.(m?js|node)$/,
            parser: { amd: false },
            use: {
              loader: '@marshallofsound/webpack-asset-relocator-loader',
              options: {
                outputAssetBase: 'native_modules',
              },
            },
          },
`?
