### ISSUE TITLE
Electron issues

### ISSUE THREAD

**Issue by ColdAssass1n** [TimelordUK/node-sqlserver-v8#198]
Hello,

I'm having an issue using your plugin with the latest version of electron.

This is my current package.json
`"dependencies": {​​
    "@angular/animations": "~11.2.4",
    "@angular/cdk": "^11.2.3",
    "@angular/common": "~11.2.4",
    "@angular/compiler": "~11.2.4",
    "@angular/core": "~11.2.4",
    "@angular/forms": "~11.2.4",
    "@angular/material": "^11.2.3",
    "@angular/platform-browser": "~11.2.4",
    "@angular/platform-browser-dynamic": "~11.2.4",
    "@angular/router": "~11.2.4",
    "node-powershell": "^4.0.0",
    "rxjs": "~6.6.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3",
    "express": "~4.16.4"
  }​​,

  "devDependencies": {​​
    "@angular-devkit/build-angular": "^0.1100.7",
    "@angular/cli": "^11.2.2",
    "@angular/compiler-cli": "^11.2.3",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.20.4",
    "codelyzer": "^6.0.0-next.1",
    "electron": "^11.3.0",
    "electron-builder": "22.9.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "msnodesqlv8": "^2.0.11",
    "mssql": "^6.3.1",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "^4.1.5"
  }​​,`

The error I am receiving after performing the update, I get this error:

`
Error: Module did not self-register: '\\?\C:\Workspace\SEPA\node_modules\msnodesqlv8\build\Release\sqlserverv8.node'.
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at C:\Workspace\SEPA\node_modules\msnodesqlv8\lib\connection.js:10:21
at Object.<anonymous> (C:\Workspace\SEPA\node_modules\msnodesqlv8\lib\connection.js:450:3)
`

Any ideas on how to fix? Thanks!

**Comment by TimelordUK** [comment]
have you tried any previous versions of 11 i.e. is it specifically latest ?

What OS are you using?

**Comment by ColdAssass1n** [comment]
I don't believe it was working on 11.3.0 and 11.2.0 and it did not work. I am using Microsoft Windows 10 Pro x64. Thanks!

**Comment by TimelordUK** [comment]
have you run $ node_modules.bin\electron-rebuild as below.

``cmd
$ yarn start
yarn run v1.22.4
$ electron .

App threw an error during load
Error: Module did not self-register: '\\?\C:\Users\\dev\js\electron\electron-quick-start\node_modules\msnodesqlv8\build\Release\sqlserverv8.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at C:\Users\\dev\js\electron\electron-quick-start\node_modules\msnodesqlv8\lib\connection.js:10:21
    at Object.<anonymous> (C:\Users\\dev\js\electron\electron-quick-start\node_modules\msnodesqlv8\lib\connection.js:450:3)
Terminate batch job (Y/N)? C:\Users\\dev\js\electron\electron-quick-start\node_modules\electron\dist\electron.exe exited with signal SIGINT

Terminate batch job (Y/N)?
Terminate batch job (Y/N)? node --version

@DesktopN C:\Users\\dev\js\electron\electron-quick-start
$ node --version
v15.8.0

**@DesktopN C:\Users\\dev\js\electron\electron-quick-start
$ node_modules\.bin\electron-rebuild
√ Rebuild Complete**

@DesktopN C:\Users\\dev\js\electron\electron-quick-start
$
@DesktopN C:\Users\\dev\js\electron\electron-quick-start
$ yarn start
yarn run v1.22.4
$ electron .

(node:8724) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

**Comment by Stihl** [comment]
> have you run $ node_modules.bin\electron-rebuild as below.
> 
> ```batchfile
> $ yarn start
> yarn run v1.22.4
> $ electron .
> 
> App threw an error during load
> Error: Module did not self-register: '\\?\C:\Users\\dev\js\electron\electron-quick-start\node_modules\msnodesqlv8\build\Release\sqlserverv8.node'.
>     at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
>     at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
>     at Module.load (internal/modules/cjs/loader.js:992:32)
>     at Module._load (internal/modules/cjs/loader.js:885:14)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
>     at Module.require (internal/modules/cjs/loader.js:1032:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at C:\Users\\dev\js\electron\electron-quick-start\node_modules\msnodesqlv8\lib\connection.js:10:21
>     at Object.<anonymous> (C:\Users\\dev\js\electron\electron-quick-start\node_modules\msnodesqlv8\lib\connection.js:450:3)
> Terminate batch job (Y/N)? C:\Users\\dev\js\electron\electron-quick-start\node_modules\electron\dist\electron.exe exited with signal SIGINT
> 
> Terminate batch job (Y/N)?
> Terminate batch job (Y/N)? node --version
> 
> @DesktopN C:\Users\\dev\js\electron\electron-quick-start
> $ node --version
> v15.8.0
> 
> **@DesktopN C:\Users\\dev\js\electron\electron-quick-start
> $ node_modules\.bin\electron-rebuild
> √ Rebuild Complete**
> 
> @DesktopN C:\Users\\dev\js\electron\electron-quick-start
> $
> @DesktopN C:\Users\\dev\js\electron\electron-quick-start
> $ yarn start
> yarn run v1.22.4
> $ electron .
> 
> (node:8724) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
> ```
> 
> ![image](https://user-images.githubusercontent.com/7300251/110174684-608ac280-7df8-11eb-9f24-4dfe8c77c75a.png)

Is this issue due to electron? I need a bit of clarification because for some reason my node_modules\.bin\electron-rebuild doesnt exist. and i just came across this issue when trying to change to a windows authentication.

**Comment by ColdAssass1n** [comment]
We decided to go a different path and do SQL through powershell. I did remember my colleague told me he tried the rebuild and it still did not work. Hope others have better luck.

**Comment by Stihl** [comment]
I have the same issue, But node_modules\.bin\electron-rebuild does not exist.
I am using node V12.
this breaks my program significantly because the client is updating to SQL Server 2019 and wants to use windows auth.

ATM im going to try and look for my own fix but any other commentary on how this can be resolved is much appreciated.

**Comment by TimelordUK** [comment]
you need to add electron-rebuild as a dependency and install via npm

the version of node you run on command line say 15 is not the same as version electron uses - this library is compiled cpp and hence you need installed the version for electron and not for node - this is what this module will do, if it doesnt work you do not have correct version installed of this module

"electron-rebuild": "^2.3.4",

you can expect to see a meta file installed as below alongside the binary if this step has worked

which contains something like x64--82


![image](https://user-images.githubusercontent.com/7300251/111376212-124aae80-8697-11eb-9796-1c0aea510544.png)

**Comment by Stihl** [comment]
Thank you very much, sorry i deleted my previous two posts after a few more tries.

This helps a lot because i realized that even though i executed the npm install both normally and with --save-dev it never actually installed electron-rebuild.
I just ran the install with --save-dev and it seems to work now.

**Comment by TimelordUK** [comment]
this is resolved we use electron-rebuild to make lib work with electron see release page electron demo app
