### ISSUE TITLE
Bulk Insert: String Length of exactly 4k characters fails with 'Invalid Precision Value'

### ISSUE THREAD

**Issue by bsEmo** [TimelordUK/node-sqlserver-v8#200]
When running a bulk insert through the table functionality with a column of varchar(max) and a string of exactly 4k characters the call will error with message "Invalid Precision Value". Created a similar issue a few months ago, but was only fixed for query and not bulk insert (https://github.com/TimelordUK/node-sqlserver-v8/issues/184). I have also been able to replicate in a simple fashion:

```
"use strict";
const mssql = require("mssql/msnodesqlv8");

const STR_LEN = 4000;
const str = "1".repeat(STR_LEN);

mssql
  .connect({
    driver: "msnodesqlv8",
    server: "...",
    database: "...",
    options: {
      trustedConnection: true,
      useUTC: true
    }
  })
  .then(() => {
    const table = new mssql.Table("table1");

    // of type varchar(max)
    table.columns.add("Column1", mssql.TYPES.VarChar(), {
      nullable: false
    });

    table.rows.add(str.repeat(4000));

    return new mssql.Request().bulk(table);
  });
```

```
Error: RequestError: Invalid precision value
    at handleError (C:\WIP\aa-tests\mssql-testing\node_modules\mssql\lib\msnodesqlv8\request.js:258:21)
    at StreamEvents.emit (events.js:198:13)
    at errors.forEach.err (C:\WIP\aa-tests\mssql-testing\node_modules\msnodesqlv8\lib\reader.js:37:20)
    at Array.forEach (<anonymous>)
    at routeStatementError (C:\WIP\aa-tests\mssql-testing\node_modules\msnodesqlv8\lib\reader.js:30:14)
    at invokeObject.end (C:\WIP\aa-tests\mssql-testing\node_modules\msnodesqlv8\lib\reader.js:209:11)
    at freeStatement (C:\WIP\aa-tests\mssql-testing\node_modules\msnodesqlv8\lib\driver.js:183:13)
    at cppDriver.freeStatement (C:\WIP\aa-tests\mssql-testing\node_modules\msnodesqlv8\lib\driver.js:163:13)
```
Software versions
NodeJS: v10.16.0
node-mssql: 6.3.1
SQL Server: Microsoft SQL Server 2016 (SP2-CU11-GDR) (KB4535706) - 13.0.5622.0 (X64)
Dec 15 2019 08:03:11
Copyright (c) Microsoft Corporation
Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 (Build 9600: ) (Hypervisor)

**Comment by TimelordUK** [comment]
should be fixed in https://github.com/TimelordUK/node-sqlserver-v8/releases/tag/v2.0.12

**Comment by bsEmo** [comment]
Looks great, thanks!
