### ISSUE TITLE
Error installing msnodesqlv8 in windows 10 local machine

### ISSUE THREAD

**Issue by mfakboo** [TimelordUK/node-sqlserver-v8#224]
Hi,
I'm getting the below error while trying to install msnodesqlv8 in windows 10  pro. Please advise.

npm i msnodesqlv8
npm ERR! code 1
npm ERR! path C:\Users\faisal\Desktop\mssql-nodejs\node_modules\msnodesqlv8
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install WARN install unexpected end of file
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.6 found at "C:\Users\faisal\AppData\Local\Programs\Python\Python38\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\faisal\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\faisal\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\faisal\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\faisal\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\faisal\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\faisal\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\faisal\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\faisal\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\faisal\Desktop\mssql-nodejs\node_modules\msnodesqlv8
npm ERR! gyp ERR! node -v v16.9.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\faisal\AppData\Local\npm-cache\_logs\2021-11-10T18_06_55_362Z-debug.log

**Comment by TimelordUK** [comment]
what  output do you get when running with verbose on prebuild i.e.

the idea is you do not need to rebuild the binary - it will either take from cache or download from git the correct version unless it does not exist in which case it will try to rebuild natively on your machine which requires the VS studio compiler - which is not present hence it has failed.

as below from the msnodesqlv8 folder

```cmd
@me ➜ published node_modules\.bin\prebuild-install msnodesqlv8 --verbose
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info install --build-from-source specified, not attempting download.

@me ➜ published cd .\node_modules\msnodesqlv8\

@me ➜ msnodesqlv8 ..\.bin\prebuild-install  --verbose
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info looking for local prebuild @ prebuilds\msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c8b49-msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz
prebuild-install http request GET https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.2/msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz
prebuild-install http 200 https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.2/msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c8b49-msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz.7816-7f0d5457572f.tmp
prebuild-install info renaming to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c8b49-msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c8b49-msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz
prebuild-install WARN install unexpected end of file

@me ➜ msnodesqlv8 pwd


Path
----
C:\Users\me\dev\js\published\node_modules\msnodesqlv8

@me ➜ msnodesqlv8 dir .\build\Release\

    Directory:  C:\Users\me\dev\js\published\node_modules\msnodesqlv8\build\Release

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        10/11/2021     18:31        1   obj
-a---        10/11/2021     18:32      841   sqlserverv8.exp
-a---        10/11/2021     18:32     7.86MB sqlserverv8.iobj
-a---        10/11/2021     18:32     2.03MB sqlserverv8.ime
-a---        10/11/2021     18:32     1.87KB sqlserverv8.lib
-a---        10/11/2021     18:34     1.28MB sqlserverv8.node
-a---        10/11/2021     18:32     8.39MB sqlserverv8.me
```

**Comment by AJSchat** [comment]
Hi there,

I was running into the same issues when trying to install the latest package (2.4.2), even when running a supported Node/NPM combination. Installing the latest package will always try to build the binary locally.

I believe this is due to the packages in Github being corrupt; I can also see this in the log you pasted:

`prebuild-install info unpacking @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c8b49-msnodesqlv8-v2.4.2-node-v93-win32-x64.tar.gz
prebuild-install WARN install unexpected end of file`

When downloading any of the files published for 2.4.2, my archive tool is giving the same errors when trying to test or unpack, e.g. the following file: https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.2/msnodesqlv8-v2.4.2-node-v93-linux-x64.tar.gz

Trying the binary published for 2.4.1 also results in an error (for v93-linux-x64), the windows one for 2.4.1 seems fine however (v93-win32-x64) when installing either through npm or testing the downloaded archive in my archive tool. Both linux and windows appear to be working correctly for the 2.4.0 release.

I think it's a matter of re-releasing and/or re-uploading the pre-compiled binaries so the archives can be unpacked locally without errors.

**Comment by TimelordUK** [comment]
ok I re-released the build with all binaries

looking at a rerun of test server looks like all builds on win . linux run tests without building.

```bash
@me ➜ msnodesqlv8 git(master) .\node_modules\.bin\prebuild-install --verbose
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info looking for local prebuild @ prebuilds\msnodesqlv8-v2.4.3-node-v102-win32-x64.tar.gz
prebuild-install info found local prebuild
prebuild-install info unpacking @ prebuilds\msnodesqlv8-v2.4.3-node-v102-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\me\dev\js\sql\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
prebuild-install info unpack required C:\Users\me\dev\js\sql\node_modules\msnodesqlv8\build\Release\sqlserverv8.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```

**Comment by ruessej** [comment]
I have the same problem with version 2.4.4

**Comment by TimelordUK** [comment]
can you ensure your npm cache is deleted and run with verbose

I have just run and it seems OK - if you have a cached corrupted tar file installed it will not work 

```cmd
rem delete this folder C:\Users\me\AppData\Local\npm-cache
@me ➜ msnodesqlv8 .\node_modules\.bin\prebuild-install --verbose
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info looking for local prebuild @ prebuilds\msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install http request GET https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.4/msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install http 200 https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.4/msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz.14204-ebf6f47c57808.tmp
prebuild-install info renaming to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\me\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
prebuild-install info unpack required C:\Users\me\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```

**Comment by ruessej** [comment]
I removed the cache from npm and yarn but it still didn't work. (It all worked in the last version)

```cmd
verbose 62.6675418 Error: C:\Server\node_modules\msnodesqlv8: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: C:\Server\node_modules\msnodesqlv8
Output:
prebuild-install WARN install unexpected end of file
```

**Comment by TimelordUK** [comment]
which version of node is it you are u

**Comment by ruessej** [comment]
v16.11.1

**Comment by TimelordUK** [comment]
you need --verbose added to the prebuild-install --verbose to see actual
output of prebuild

**Comment by ruessej** [comment]
This is the complete error message

```cmd
error C:\Server\node_modules\msnodesqlv8: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: C:\Server\node_modules\msnodesqlv8
Output:
prebuild-install WARN install unexpected end of file

C:\Server\node_modules\msnodesqlv8>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.2.0
gyp info using node@16.11.1 | win32 | x64
gyp info find Python using Python version 3.10.1 found at "C:\Users\me\AppData\Local\Programs\Python\Python310\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Server\node_modules\msnodesqlv8
gyp ERR! node -v v16.11.1
gyp ERR! node-gyp -v v8.2.0
gyp ERR! not ok
```

**Comment by TimelordUK** [comment]
right but the messages
Output:prebuild-install WARN install unexpected end of file implies it is trying to use a local version of the file that is corrupted. I have just installed on windows your version of node and it works
you need out of following
@me ➜ msnodesqlv8 npm install --g prebuild-install

added 59 packages, and audited 61 packages in 3s

found 0 vulnerabilities

```cmd
@me ➜ msnodesqlv8 prebuild-install --verbose msnodesqlv8
prebuild-install info begin Prebuild-install version 7.0.0
prebuild-install info looking for local prebuild @ prebuilds\msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install http request GET https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.4/msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install http 200 https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.4/msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz.11536-a64cfc4cab573.tmp
prebuild-install info renaming to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\me\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
prebuild-install info unpack required C:\Users\me\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```

**Comment by ruessej** [comment]
```cmd
C:\Server>prebuild-install --verbose msnodesqlv8
prebuild-install info begin Prebuild-install version 7.0.0
prebuild-install info looking for local prebuild @ prebuilds\server-v1.0.0-node-v93-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\034308-server-v1.0.0-node-v93-win32-x64.tar.gz
prebuild-install http request GET undefined/releases/download/v1.0.0/server-v1.0.0-node-v93-win32-x64.tar.gz
prebuild-install http 400 undefined/releases/download/v1.0.0/server-v1.0.0-node-v93-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=16.11.1 runtime=node arch=x64 libc= platform=win32)
```

**Comment by ruessej** [comment]
Thanks now it worked 👍🏻

**Comment by TimelordUK** [comment]
you are not in right folder

you need to be in  node_modules\msnodesqlv8
then run command - from above it is not looking for msnodesqlv8 but
server-v1.0.0

**Comment by TimelordUK** [comment]
ok great sorry did not see your above comment in time!

**Comment by NoelAbrahams** [comment]
@TimelordUK I think there is a problem somewhere with msnodesqlv8 and node version 16.13.1 playing together.

I ran into the same errors and wasn't able to resolve it with with the this: `msnodesqlv8@2.0.8  npm install prebuild-install` (that's the version we want).

The errors were similar to those reported above:

```
npm ERR! code 1
npm ERR! path C:\fakeproject\node_modules\msnodesqlv8
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=16.13.1 runtime=node arch=x64 libc= platform=win32)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
...etc
```

We were able to install without error after rolling NodeJS back to version 15.2.1.

I'm on a Windows 10 Pro machine.

I'm sorry I can't help debug this issue further; we rolled NodeJS back for another reason.

But let me know.

Thanks
Noel

**Comment by TimelordUK** [comment]
this version does not work with node 16- it is working with latest 2.4.4,
there probably was not even that version of node available when this shipped

else you would have to build code locally against the src for that build

.

**Comment by NoelAbrahams** [comment]
I should have mentioned that I got the same errors with 2.4.4 as well. I basically tried different things to get it installed.

**Comment by TimelordUK** [comment]
I have just instaled on win 10 seems to work for 16.13.1

```cmd
@me ➜ published node --version
v16.13.1

@me ➜ published uname
MSYS_NT-10.0-19044

@me ➜ published npm install msnodesqlv8

added 59 packages, and audited 60 packages in 8s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

@me ➜ published cd .\samples\

@me ➜ samples cd .\javascript\

@me ➜ javascript node .\simple-demo.js
rows.length 37 elapsed 80
rows.length 37 elapsed 10

@me ➜ msnodesqlv8 .\node_modules\.bin\prebuild-install --verbose
prebuild-install info begin Prebuild-install version 6.1.4
prebuild-install info looking for local prebuild @ prebuilds\msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install http request GET https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.4/msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install http 200 https://github.com/TimelordUK/node-sqlserver-v8/releases/download/v2.4.4/msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz.18736-8d5098c66daac.tmp
prebuild-install info renaming to @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\me\AppData\Roaming\npm-cache\_prebuilds\5c33f1-msnodesqlv8-v2.4.4-node-v93-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\me\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node
prebuild-install info unpack required C:\Users\me\dev\js\published\node_modules\msnodesqlv8\build\Release\sqlserverv8.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```

**Comment by DvoeglazovIlya** [comment]
I have the same problem.
npm -v 7.21.1
node -v 16.14.0
Microsoft Sql server management studio 17

```
error D:\Projects\mfc_social_network\backend\node_modules\msnodesqlv8: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: D:\Projects\mfc_social_network\backend\node_modules\msnodesqlv8
Output:
prebuild-install WARN install unexpected end of file

D:\Projects\mfc_social_network\backend\node_modules\msnodesqlv8>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.0 | win32 | x64
gyp info find Python using Python version 3.7.3 found at "C:\Python37\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\mfc_social_network\backend\node_modules\msnodesqlv8
```

For resolving this problem I make this things:
`npm install --g prebuild-install`
Then I update msnodesqlv8 from ^2.2.0 to ^2.4.7
I don't know help it on not, but before I instal ODBC Driver (https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15)

The same problem was in wsl (ubunto) to. I just run this script https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#ubuntu18

**Comment by TimelordUK** [comment]
Closing this it’s not relevant to new version
