### ISSUE TITLE
Install msnodesqlv8 offline system

### ISSUE THREAD

**Issue by vipeesh** [TimelordUK/node-sqlserver-v8#263]
I have installed this package in my local machine where i have access to internet and it worked well. Now we wanted to move the changes in windows server where we don't have internet access. 

First i tried by copying installed folder from my local machine to server. But am getting following error

Application has thrown an uncaught exception and is terminated:
Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at connectionModule (F:\Sony Live Sites\SONY_RIGHTS\SONY_RIGHTS\node_modules\msnodesqlv8\lib\connection.js:10:21)
    at Object.<anonymous> (F:\Sony Live Sites\SONY_RIGHTS\SONY_RIGHTS\node_modules\msnodesqlv8\lib\connection.js:679:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\Sony Live Sites\SONY_RIGHTS\SONY_RIGHTS\node_modules\msnodesqlv8\lib\sql.js:22:12)

Now we are trying to install by packaging this module for offline using npm-pack-all
In this one also we are getting some errors

Can you guys please help us or give some suggestion to install this module on offline machine? thanks

**Comment by TimelordUK** [comment]
First thing to note is when you install locally the module downloaded
matches the version of node running. Because we use cpp each version of
node has its own compiled module.

The downloaded module is placed in build release folder. When you package
and deploy you are probably picking up this module.  The error you see is
most likely down to version of node on server is not same as that used when
module Was downloaded.  These modules are all stored on release page of git
release.

If you first ensure node version and architecture are same then should be
ok. Else somehow you need to manually patch the compiled build when you
release on build box.

**Comment by vipeesh** [comment]
Thanks for the quick reply. I guess the version are different. I will make sure both are same version and check it
