### ISSUE TITLE
uncaughtException: Cannot read properties of null (reading 'query')

### ISSUE THREAD

**Issue by nqb9** [TimelordUK/node-sqlserver-v8#317]
Hello, unfortunately I got an uncaught exception in my application. I was using a pool to query SQL Server database multiple times, also with pause and cancel query, and got the problem:
![image](https://github.com/TimelordUK/node-sqlserver-v8/assets/141388760/ae26ad0b-533f-4132-9ca0-75ea353e5a45)

It is on the line **646** in **lib/pool.js**

The description.connection is **null** and look like it is set to **null** only in this place:
![image](https://github.com/TimelordUK/node-sqlserver-v8/assets/141388760/7f58fb31-ff89-4bbf-a76a-8a5cac8e2e62)

My msnodesqlv8 version: **4.1.1**

Looking forward to your response. Thank you.

**Comment by nqb9** [comment]
The whole error log is:
`TypeError: Cannot read properties of null (reading 'query')
    at heartbeat (C:\IMS-PROJECTS\QA\QService\node_modules\msnodesqlv8\lib\pool.js:646:42)
    at Timeout._onTimeout (C:\IMS-PROJECTS\QA\QService\node_modules\msnodesqlv8\lib\pool.js:593:15)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7) {
    "error": {},
    "stack": "TypeError: Cannot read properties of null (reading 'query')\n    at heartbeat (C:\\IMS-PROJECTS\\QA\\QService\\node_modules\\msnodesqlv8\\lib\\pool.js:646:42)\n    at Timeout._onTimeout (C:\\IMS-PROJECTS\\QA\\QService\\node_modules\\msnodesqlv8\\lib\\pool.js:593:15)\n    at listOnTimeout (node:internal/timers:561:11)\n    at processTimers (node:internal/timers:502:7)",
    "exception": true,
    "date": "Mon Dec 18 2023 14:52:18 GMT+0700 (Indochina Time)",
    "process": {
        "pid": 2740,
        "uid": null,
        "gid": null,
        "cwd": "C:\\IMS-PROJECTS\\QA\\QService",
        "execPath": "C:\\Program Files\\nodejs\\node.exe",
        "version": "v16.19.0",
        "argv": [
            "C:\\Program Files\\nodejs\\node.exe",
            "C:\\IMS-PROJECTS\\QA\\QService\\dist\\server\\src\\index.js",
            "--logLevel",
            "debug"
        ],
        "memoryUsage": {
            "rss": 431636480,
            "heapTotal": 349945856,
            "heapUsed": 346579832,
            "external": 20484001,
            "arrayBuffers": 18993878
        }
    },
    "os": {
        "loadavg": [
            0,
            0,
            0
        ],
        "uptime": 369710
    },
    "trace": [
        {
            "column": 42,
            "file": "C:\\IMS-PROJECTS\\QA\\QService\\node_modules\\msnodesqlv8\\lib\\pool.js",
            "function": "heartbeat",
            "line": 646,
            "method": null,
            "native": false
        },
        {
            "column": 15,
            "file": "C:\\IMS-PROJECTS\\QA\\QService\\node_modules\\msnodesqlv8\\lib\\pool.js",
            "function": "Timeout._onTimeout",
            "line": 593,
            "method": "_onTimeout",
            "native": false
        },
        {
            "column": 11,
            "file": "node:internal/timers",
            "function": "listOnTimeout",
            "line": 561,
            "method": null,
            "native": false
        },
        {
            "column": 7,
            "file": "node:internal/timers",
            "function": "processTimers",
            "line": 502,
            "method": null,
            "native": false
        }
    ]
}`

**Comment by TimelordUK** [comment]
im not sure when I can look at this,  i current;y have little time available 

it would seem we somehow are closing the connection as part of considering it idle but leaving the description with its connection marked null.

do we still see the problem if we set 
inactivityTimeoutSecs

to be very high so connections in pool are always held open?

**Comment by nqb9** [comment]
Thank you very much for the response and happy holidays!

I tried with **inactivityTimeoutSecs = 60**, but unfortunately I still got problem after some queries.

The problem is not the exact same as above, but still the **description.connection is null**, which leads to the error

**log**
`"stack":"TypeError: Cannot read properties of null (reading 'query')\n    at getTheQuery (D:\\IMS\\Repos\\QService\\node_modules\\msnodesqlv8\\lib\\pool.js:321:28)\n    at item (D:\\IMS\\Repos\\QService\\node_modules\\msnodesqlv8\\lib\\pool.js:338:19)\n    at D:\\IMS\\Repos\\QService\\node_modules\\msnodesqlv8\\lib\\pool.js:389:15","message":"Cannot read properties of null (reading 'query')"`

**src from log**
![image](https://github.com/TimelordUK/node-sqlserver-v8/assets/141388760/b49eb168-f077-42b5-b180-1aea24d1e79a)
![image](https://github.com/TimelordUK/node-sqlserver-v8/assets/141388760/0fb468aa-96f4-496e-bebf-1c80e6736c3e)
![image](https://github.com/TimelordUK/node-sqlserver-v8/assets/141388760/4cce592b-34e1-4b05-9817-ffb871b70adb)

**Comment by TimelordUK** [comment]
Fixed in **5.2.3**.

This was a genuine bug and it had been there a long time — apologies it sat open. Your diagnosis was right: `park()` is indeed the only place that sets `description.connection = null`. What wasn't obvious is how a parked description was still reachable, since `park()` removes it from the idle list at the same time. It turns out the description was in that list *twice*.

### What was happening

A statement that fails during dispatch raises **both** `error` and `done` (in `lib/reader.js`, the dispatch catch emits `error`, then `done`, then `free`). The pool's `heartbeat()` acted on both:

- `error` → `recreate()` → `checkin`
- `done` → `checkin`

Both checked in the *same* `PoolDescription`, so it ended up in `idle` twice. `park()` then closed the connection and nulled it through one of the two references, splicing only that one out. The duplicate stayed in `idle` pointing at the same object — now with `connection === null`. The next checkout dereferenced it:

```
TypeError: Cannot read properties of null (reading 'query')
    at heartbeat (lib/pool.js)
```

This also explains the two different stacks you posted. Your second one (`getTheQuery`) is the same root cause surfacing through the query path instead of the heartbeat path — whichever code checked out the stale duplicate first is the one that threw.

And it explains why raising `inactivityTimeoutSecs` didn't help: that only delays parking, it doesn't stop the duplication. The bad state was already there, waiting.

### The fix

Two parts, in `lib/pool.js`:

1. A `settled` flag in `heartbeat()`, so only the first of `error`/`done` returns a description to the pool.
2. A guard in `checkin()` that refuses a description already present in `idle` or `parked` — making the invariant structural rather than dependent on every call site behaving.

Reproducing this reliably meant stubbing the driver so the `error`+`done` ordering is deterministic. That harness landed as `test/pool-description-lifecycle.test.js`; it needs no SQL Server and fails with the exact error above when the fix is reverted.

Two unrelated defects turned up in the same file while investigating and were fixed alongside: `close()` was mapping `promises.close` without invoking it, so idle connections were never actually closed at pool shutdown; and `promotePause()` tested a property `PoolWorkItem` doesn't have.

You were on 4.1.1, so 5.2.3 is a sizeable jump — worth a look at the changelog for anything else that affects you. Closing, but reopen or file a new issue if you still see it.
