### ISSUE TITLE
Node Version 9.2.0 Issue

### ISSUE THREAD

**Issue by DamolAAkinleye** [TimelordUK/node-sqlserver-v8#53]
When the package is used in Node 9.2.0 there is an issue that crops up as below.

Please is there any work around this. This is surely not the expected behaviour.

Unhandled rejection Error: None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7 or 8 ?
    at failIfNoBinaryExported (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\msnodesqlv8\lib\bootstrap.js:61:15)
    at Object.liveLoad (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\msnodesqlv8\lib\bootstrap.js:48:5)
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\msnodesqlv8\lib\bootstrap.js:77:12)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\msnodesqlv8\lib\connection.js:10:19
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\msnodesqlv8\lib\connection.js:449:2)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\msnodesqlv8\lib\sql.js:20:10)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\mssql\lib\msnodesqlv8.js:3:19)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\mssql\msnodesqlv8.js:1:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\e2e\pages\utils\databaseabstraction\iViewPlus-database-helper.ts:2:13)
    at Module._compile (module.js:641:30)
    at Module.m._compile (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:652:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\e2e\pages\utils\databaseabstraction\query-manager-database-helper.ts:1:1)
    at Module._compile (module.js:641:30)
    at Module.m._compile (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:652:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\e2e\stepdefinitions\querymanagerStep.ts:3:1)
    at Module._compile (module.js:641:30)
    at Module.m._compile (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:652:10)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\cucumber\src\cli\index.js:61:42
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\cucumber\src\cli\index.js:61:22)
    at Cli.<anonymous> (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\cucumber\src\cli\index.js:76:37)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\development\iViewPlus\iViewPlus.External.Web.v2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by TimelordUK** [comment]
If you look at GitHub master I have checked in some node 9 binaries. For now if you drop these into bin folder it should work. I will release to nom shortly.

**Comment by Eduportal** [comment]
Thanks for the swift reply. I will wait for the  NPM package as it is failing on  my build server which I have no access to push binaries to.

**Comment by kevinkuszyk** [comment]
@TimelordUK any chance you can push this to npm?

**Comment by TimelordUK** [comment]
sorry about the delay, i have pushed a release to npm which includes v9 compatibility

**Comment by kevinkuszyk** [comment]
Thanks, much appreciated.

**Comment by TimelordUK** [comment]
closing as we look good now.

**Comment by NickersWeb** [comment]
Also get this error on npm start.  
https://www.screencast.com/t/hPFBDRuLxfY
Not sure what you mean about the fix. As I'm new to developing to this technology. 

My version of msnodesqlv8 is 5.5.1 
My version of mssql is 5.5.1

Running it on a electron app.
