### ISSUE TITLE
Can't load msnodesqlv8

### ISSUE THREAD

**Issue by tonyguinta** [TimelordUK/node-sqlserver-v8#84]
I have installed msnodesqlv8 v0.6.9 on node v11.0.0, and receive an error when I try to run a script that simply contains:

`const sql = require("msnodesqlv8");`

Error:

```
E:\Tony\Development\Node.js\playground\node_modules\msnodesqlv8\lib\bootstrap.js:63
        throw new Error('None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7, 8 or 9 ?')
        ^

Error: None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7, 8 or 9 ?
    at failIfNoBinaryExported (E:\Tony\Development\Node.js\playground\node_modules\msnodesqlv8\lib\bootstrap.js:63:15)
    at Object.liveLoad (E:\Tony\Development\Node.js\playground\node_modules\msnodesqlv8\lib\bootstrap.js:50:5)
    at Object.<anonymous> (E:\Tony\Development\Node.js\playground\node_modules\msnodesqlv8\lib\bootstrap.js:79:12)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
I've tried uninstalling and reinstalling msnodesqlv8, and the install seems to go fine, but the module still won't seem to load. Any clues will be greatly appreciated.

**Comment by TimelordUK** [comment]
I will release support for version 11 node in next day or two. Thanks for letting me know.

**Comment by TimelordUK** [comment]
this should now work on 0,6.10

**Comment by tonyguinta** [comment]
Confirmed that it's working now. Thanks!
