### ISSUE TITLE
"Error: None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7, 8 or 9 ?","at failIfNoBinaryExported 

### ISSUE THREAD

**Issue by sivadgit** [TimelordUK/node-sqlserver-v8#85]
I have installed msnodesqlv8 v0.6.9 on node v11.1.0, and receive an error when I try to run a script that simply contains:

const sql = require("msnodesqlv8");

In our project we are using web-pack and server less lambda service.

{"errorMessage":"Error while loading CapacityService","errorType":"Error","stackTrace":["Error: None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7, 8 or 9 ?","at failIfNoBinaryExported (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\msnodesqlv8\\lib\\bootstrap.js:69:1)","at Object.liveLoad (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\msnodesqlv8\\lib\\bootstrap.js:56:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\msnodesqlv8\\lib\\bootstrap.js:86:1)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\msnodesqlv8\\lib\\connection.js:10:1","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\msnodesqlv8\\lib\\connection.js:452:2)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\msnodesqlv8\\lib\\sql.js:22:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\index.js:74866:30)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\mssql\\lib\\msnodesqlv8.js:3:1)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\node_modules\\mssql\\msnodesqlv8.js:1:1)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\src\\service_module\\Data\\datalayer.ts:9:13)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\src\\service_module\\services\\capacityservice\\data_layer\\GetMasterData.ts:5:1)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\src\\service_module\\services\\capacityservice\\buisness_layer\\CapacityMasterData.ts:2:1)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\src\\service_module\\services\\capacityservice\\index.ts:1:1)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\src\\index.ts:4:1)","at __webpack_require__ (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:19:1)","at C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\webpack:\\webpack\\bootstrap 009323ffe2d87b058a45:62:1","at Object.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\build\\src\\index.js:66:10)","at Module._compile (internal/modules/cjs/loader.js:707:30)","at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)","at Module.load (internal/modules/cjs/loader.js:605:32)","at tryModuleLoad (internal/modules/cjs/loader.js:544:12)","at Function.Module._load (internal/modules/cjs/loader.js:536:3)","at Module.require (internal/modules/cjs/loader.js:643:17)","at require (internal/modules/cjs/helpers.js:22:18)","at Object.createHandler (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\serverless-offline\\src\\functionHelper.js:104:21)","at handler (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\serverless-offline\\src\\index.js:556:40)","at Object.internals.handler (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\handler.js:96:36)","at request._protect.run (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\handler.js:30:23)","at module.exports.internals.Protect.internals.Protect.run (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\protect.js:64:5)","at exports.execute (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\handler.js:24:22)","at each (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\items\\lib\\index.js:36:13)","at done (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\items\\lib\\index.js:28:25)","at module.exports.internals.Auth.internals.Auth._authenticate (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\auth.js:210:16)","at internals.Auth.authenticate (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\auth.js:202:17)","at each (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\items\\lib\\index.js:36:13)","at done (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\items\\lib\\index.js:28:25)","at internals.state (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\route.js:357:16)","at each (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\items\\lib\\index.js:36:13)","at Object.exports.serial (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\items\\lib\\index.js:39:9)","at internals.Request._lifecycle (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\request.js:387:11)","at internals.Request._execute (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\request.js:302:21)","at Domain.request._protect.enter (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\connection.js:261:25)","at Domain.run (domain.js:342:14)","at module.exports.internals.Protect.internals.Protect.enter (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\protect.js:80:17)","at Server.<anonymous> (C:\\GIT_OnlineFTEBranch\\CIO_SMT_Project\\OnlineFTE\\node_modules\\hapi\\lib\\connection.js:259:30)","at Server.emit (events.js:182:13)","at Server.EventEmitter.emit (domain.js:441:20)","at parserOnIncoming (_http_server.js:657:12)"],"offlineInfo":"If you believe this is an issue with the plugin please submit it, thanks. https://github.com/dherault/serverless-offline/issues"}

**Comment by TimelordUK** [comment]
https://github.com/TimelordUK/node-sqlserver-v8/issues/84

can you try latest version 0.6.11? this should be addressed in that version as in previous issue

**Comment by sivadgit** [comment]
Hi,
I have updated with 0.6.11 version still i am getting same error. 
Note:
Without Web-pack its working fine but if i include Web-pack , i am blocking with this error. We are struggling with this error for past 10 days.

FYR:
"dependencies": {
    "aws-sdk": "2.58.0",
    "date-diff": "^0.2.1",
    "json2typescript": "^1.0.6",
    "latest": "^0.2.0",
    "msnodesqlv8": "^0.6.11",
    "mssql": "^4.2.1",
    "node": "^11.1.0",
    "promise": "^8.0.1",
    "rebar-aws-oauthv2": "file:NPM-local-pkg\\rebar-aws-oauthv2"
  }

Error:
{"errorMessage":"Error while loading CapacityService","errorType":"Error","stackTrace":["Error: None of the binaries loaded successfully. Is your node version either latest 4, 5, 6, 7, 8 or 9 ?","at failIfNoBinaryExported (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\bootstrap.js:69:1)","at Object.liveLoad (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\bootstrap.js:56:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\bootstrap.js:86:1)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\connection.js:10:1","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\connection.js:452:2)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\sql.js:22:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\index.js:74866:30)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\mssql\lib\msnodesqlv8.js:3:1)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\mssql\msnodesqlv8.js:1:1)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\Data\datalayer.ts:9:13)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\services\capacityservice\data_layer\GetMasterData.ts:5:1)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\services\capacityservice\buisness_layer\CapacityMasterData.ts:2:1)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\services\capacityservice\index.ts:1:1)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\index.ts:4:1)","at webpack_require (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:19:1)","at C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap 009323ffe2d87b058a45:62:1","at Object. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\index.js:66:10)","at Module._compile (internal/modules/cjs/loader.js:707:30)","at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)","at Module.load (internal/modules/cjs/loader.js:605:32)","at tryModuleLoad (internal/modules/cjs/loader.js:544:12)","at Function.Module._load (internal/modules/cjs/loader.js:536:3)","at Module.require (internal/modules/cjs/loader.js:643:17)","at require (internal/modules/cjs/helpers.js:22:18)","at Object.createHandler (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\serverless-offline\src\functionHelper.js:104:21)","at handler (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\serverless-offline\src\index.js:556:40)","at Object.internals.handler (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\handler.js:96:36)","at request._protect.run (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\handler.js:30:23)","at module.exports.internals.Protect.internals.Protect.run (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\protect.js:64:5)","at exports.execute (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\handler.js:24:22)","at each (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:384:16)","at iterate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:36:13)","at done (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:28:25)","at module.exports.internals.Auth.internals.Auth._authenticate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\auth.js:210:16)","at internals.Auth.authenticate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\auth.js:202:17)","at each (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:384:16)","at iterate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:36:13)","at done (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:28:25)","at internals.state (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\route.js:357:16)","at each (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:384:16)","at iterate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:36:13)","at Object.exports.serial (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:39:9)","at internals.Request._lifecycle (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:387:11)","at internals.Request._execute (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:302:21)","at Domain.request._protect.enter (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\connection.js:261:25)","at Domain.run (domain.js:342:14)","at module.exports.internals.Protect.internals.Protect.enter (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\protect.js:80:17)","at Server. (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\connection.js:259:30)","at Server.emit (events.js:182:13)","at Server.EventEmitter.emit (domain.js:441:20)","at parserOnIncoming (_http_server.js:657:12)"],"offlineInfo":"If you believe this is an issue with the plugin please submit it, thanks. https://github.com/dherault/serverless-offline/issues"}

**Comment by TimelordUK** [comment]
is it possible in bootstrap.js to add a debug line in somewhere like

```javascript
    function attemptToExportBinary (filename) {
      try {
        var native = path.join(binaryDir, filename)
        module.exports = require(native)
      } catch (e) {
      }
    }
```
I assume it is failing as it is unable to locate the binary - for example what is "native" above and does that file exist after webpack has finished,

**Comment by sivadgit** [comment]
Hi,
Please find the below log:

native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v2.0.4.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v2.0.4.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v3.0.3.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.electron.v3.0.3.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v10.13.0.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v10.13.0.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v11.2.0.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v11.2.0.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v4.9.1.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v4.9.1.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v5.12.0.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v5.12.0.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v6.14.3.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v6.14.3.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v7.10.1.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v7.10.1.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v8.11.3.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v8.11.3.x64.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v9.11.2.ia32.node
native path : node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v9.11.2.x64.node

Also we captured log in  catch block, please find exception details below:

{ Error: Cannot find module "."
    at webpackMissingModule (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\bootstrap.js:59:8)
    at attemptToExportBinary (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\bootstrap.js:59:8)
    at C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\bootstrap.js:48:1
    at Array.forEach (<anonymous>)
    at Object.liveLoad (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\bootstrap.js:46:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\index.js:75416:12)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\connection.js:10:1
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\connection.js:452:2)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\msnodesqlv8\lib\sql.js:22:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\index.js:74866:30)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\mssql\lib\msnodesqlv8.js:3:1)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\node_modules\mssql\msnodesqlv8.js:1:1)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\Data\datalayer.ts:9:13)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\services\capacityservice\data_layer\GetMasterData.ts:5:1)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\services\capacityservice\buisness_layer\CapacityMasterData.ts:2:1)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\service_module\services\capacityservice\index.ts:1:1)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\src\index.ts:4:1)
    at __webpack_require__ (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:19:1)
    at C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\webpack:\webpack\bootstrap f4e213e86b9f41ffcb53:62:1
    at Object.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\build\src\index.js:66:10)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.createHandler (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\serverless-offline\src\functionHelper.js:104:21)
    at handler (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\serverless-offline\src\index.js:556:40)
    at Object.internals.handler (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\handler.js:96:36)
    at request._protect.run (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\handler.js:30:23)
    at module.exports.internals.Protect.internals.Protect.run (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\protect.js:64:5)
    at exports.execute (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\handler.js:24:22)
    at each (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:384:16)
    at iterate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:36:13)
    at done (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:28:25)
    at module.exports.internals.Auth.internals.Auth._authenticate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\auth.js:210:16)
    at internals.Auth.authenticate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\auth.js:202:17)
    at each (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:384:16)
    at iterate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:36:13)
    at done (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:28:25)
    at internals.state (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\route.js:357:16)
    at each (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:384:16)
    at iterate (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:36:13)
    at Object.exports.serial (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\items\lib\index.js:39:9)
    at internals.Request._lifecycle (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:387:11)
    at internals.Request._execute (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\request.js:302:21)
    at Domain.request._protect.enter (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\connection.js:261:25)
    at Domain.run (domain.js:342:14)
    at module.exports.internals.Protect.internals.Protect.enter (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\protect.js:80:17)
    at Server.<anonymous> (C:\GIT_OnlineFTEBranch\CIO_SMT_Project\OnlineFTE\node_modules\hapi\lib\connection.js:259:30)
    at Server.emit (events.js:182:13)
    at Server.EventEmitter.emit (domain.js:441:20)
    at parserOnIncoming (_http_server.js:657:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17) code: 'MODULE_NOT_FOUND' }

**Comment by TimelordUK** [comment]
Can you describe exactly how the webpack bundle is running. Is this required to work in a browser as http client ?  

If that is the case this module will not work as it requires a cpp compiled module that only runs in node or electron where electron behaves as a native application.

**Comment by lobster2012-user** [comment]
> D:\dev\pull\sqltabs\node_modules\msnodesqlv8\lib\bin\sqlserverv8.node.v11.2.0.x64.node
> D:\dev\pull\sqltabs\node_modules\msnodesqlv8\lib\bootstrap.js:59 Error: A dynamic link library (DLL) initialization routine failed.
> (…)

x64
node version 11.2.0
lib version 0.6.12

**Comment by mtriff** [comment]
Webpack support was added in v0.8.9.
