### ISSUE TITLE
Unhandled error event - Communication link failure

### ISSUE THREAD

**Issue by pbierkortte** [TimelordUK/node-sqlserver-v8#92]
Run environment:
- Windows [Version 10.0.16299.547]  
- Node v10.15.3
- msnodesqlv8 v0.6.12

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: [Microsoft][ODBC Driver 13 for SQL Server]Communication link failure
Emitted 'error' event at:
    at <REDACTED>\node_modules\msnodesqlv8\lib\reader.js:29:20
    at Array.forEach (<anonymous>)
    at routeStatementError (<REDACTED>\node_modules\msnodesqlv8\lib\reader.js:22:14)
    at<REDACTED>\node_modules\msnodesqlv8\lib\reader.js:176:15
    at <REDACTED>\node_modules\msnodesqlv8\lib\driver.js:162:13
    at <REDACTED>\node_modules\msnodesqlv8\lib\driver.js:152:11
```

**Comment by TimelordUK** [comment]
sorry this does not look live an issue with library itself - please re-raise after trying latest version and provide more information as to cause of this problem. Closing this.
